### Manipulating  and Comparing Arrays


# Aritmatic

In [4]:
import numpy as np

a1 = np.array([1,2,3]) 
a1

array([1, 2, 3])

In [6]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [9]:
a2 = a1 + ones
a2

array([2., 3., 4.])

In [10]:
type(a2)

numpy.ndarray

In [14]:
a3 = a1 - ones
a3

array([0., 1., 2.])

In [17]:
a4 = a1 * ones
a4

array([1., 2., 3.])

In [19]:
a5 = np.array([[1,2,3], [4,5,6]])
a5

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a6 = a4 * a5
a6

array([[ 1.,  4.,  9.],
       [ 4., 10., 18.]])

In [24]:
a7 = np.array([[[1, 2, 3], [4,5,6], [7,8,9]],
               [[10,11,12],[13,14,15], [16,17,18]]])
a7

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [26]:
a5

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
a7

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [28]:
## How can you reshape a2 to be compatible with a3?
# Search: "How to reshape numpy array"

a8 = a5 * a7

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [29]:
a1

array([1, 2, 3])

In [30]:
a1/ ones

array([1., 2., 3.])

In [31]:
a2

array([2., 3., 4.])

In [32]:
a2/a1

array([2.        , 1.5       , 1.33333333])

In [33]:
a5

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
a5/a1

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [35]:
# Floor division removes the decimals
a5//a1

array([[1, 1, 1],
       [4, 2, 2]], dtype=int32)

In [36]:
a5 **2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [37]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [38]:
a5 % 2

array([[1, 0, 1],
       [0, 1, 0]], dtype=int32)

In [39]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [40]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

Aggregation == performing the same operation on a number of things

In [42]:
list1 = [1,2,3]
type(list1)

list

In [43]:
sum(list1)

6

In [44]:
a1

array([1, 2, 3])

In [45]:
type(a1)

numpy.ndarray

In [46]:
sum(a1)

6

In [47]:
np.sum(a1)

6

Use python's methods on python data types and use Numpy methods on Numpy arrays (np.sum()) 

In [50]:
## Create a massive Numpy array
massive_array = np.random.random(100000)

In [51]:
massive_array

array([0.53679987, 0.99408613, 0.12467469, ..., 0.89764505, 0.74499585,
       0.4209306 ])

In [52]:
massive_array.size

100000

In [53]:
massive_array[:100]

array([0.53679987, 0.99408613, 0.12467469, 0.5533134 , 0.6575756 ,
       0.53957832, 0.07589841, 0.87617919, 0.94130434, 0.72825748,
       0.73079392, 0.99055296, 0.55714331, 0.86900481, 0.54178982,
       0.08343758, 0.89918348, 0.27891735, 0.15333669, 0.16333698,
       0.66661453, 0.57825012, 0.60315174, 0.16984693, 0.60776445,
       0.15545244, 0.19742029, 0.68735049, 0.15130516, 0.16509161,
       0.79177757, 0.89990609, 0.44549585, 0.1791652 , 0.81569067,
       0.0798583 , 0.89434842, 0.51756101, 0.18152916, 0.66793375,
       0.64950484, 0.04687948, 0.67770476, 0.70333948, 0.43599126,
       0.94608551, 0.92110384, 0.4301307 , 0.30447247, 0.81430292,
       0.14562918, 0.23812129, 0.11832133, 0.22939164, 0.44761729,
       0.88291866, 0.1397334 , 0.77176362, 0.44097231, 0.13620744,
       0.0599338 , 0.73451609, 0.51066602, 0.72969342, 0.9175493 ,
       0.81659143, 0.82659463, 0.69058392, 0.9469742 , 0.10623278,
       0.81321729, 0.96412598, 0.82684245, 0.88155893, 0.48604

In [54]:
massive_array[:50]

array([0.53679987, 0.99408613, 0.12467469, 0.5533134 , 0.6575756 ,
       0.53957832, 0.07589841, 0.87617919, 0.94130434, 0.72825748,
       0.73079392, 0.99055296, 0.55714331, 0.86900481, 0.54178982,
       0.08343758, 0.89918348, 0.27891735, 0.15333669, 0.16333698,
       0.66661453, 0.57825012, 0.60315174, 0.16984693, 0.60776445,
       0.15545244, 0.19742029, 0.68735049, 0.15130516, 0.16509161,
       0.79177757, 0.89990609, 0.44549585, 0.1791652 , 0.81569067,
       0.0798583 , 0.89434842, 0.51756101, 0.18152916, 0.66793375,
       0.64950484, 0.04687948, 0.67770476, 0.70333948, 0.43599126,
       0.94608551, 0.92110384, 0.4301307 , 0.30447247, 0.81430292])

In [57]:
%timeit sum(massive_array)   #Python sum()
%timeit np.sum(massive_array)   # Numpy's np.sum()

28.9 ms ± 399 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
84.5 µs ± 75.6 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [61]:
a5

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
np.mean(a2)

3.0

In [63]:
np.min(a2)

2.0

In [64]:
np.max(a2)

4.0

In [65]:
np.var(a2)

0.6666666666666666